import "./globals.css";

import type { Metadata } from "next";

import { montserrat } from "./_fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.ReactElement {
  return (
    <html lang="en" className={montserrat.variable}>
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
      </head>
      <body
        className="flex min-h-screen flex-col bg-blue-100"
        style={{
          maxHeight: "env(safe-area-inset-bottom)",
        }}
      >
        {children}
      </body>
    </html>
  );
}
